# ⚠️ No scope but only for javascript/typescript/react ect.
[["snippets"]]
name = "console.log a variable"
prefix = "cv"
body = "console.log('🚥 ~ ${1}:', ${1})"
description = "console.log a variable"

[[snippets]]
name = "Log to the console"
prefix = "log"
body = ["console.log($1);", "$0"]
description = "Log to the console"


[[snippets]]
name = "Log warning to console"
prefix = "warn"
body = ["console.warn($1);", "$0"]
description = "Log warning to the console"


[[snippets]]
name = "Log error to console"
prefix = "error"
body = ["console.error($1);", "$0"]
description = "Log error to the console"


[[snippets]]
name = "Throw Exception"
prefix = "throw"
body = ["throw new Error(\"$1\");", "$0"]
description = "Throw Exception"
